name: CI

on:
  push:
    branches: [customers]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: 18

      - name: Move to transferences service 
        run: cd transferences
      - run: npm i
      - run: npm run test