name: CI

on:
  push:
    branches: [customers]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: 18

      - name: Change directory and run a command
        working-directory: path/to/your/directory
      - run: npm i
      - run: npm run test